spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev     #开发环境
    active: 
    application: 
      name: microservice-config-dev
---
spring: 
  profiles: dev     #测试环境
    active: 
    application: 
      name: microservice-config-test
      
# 文件必须以UTF-8格式保存
